// Fix: Import firebase to resolve 'firebase' not defined errors.
import firebase from 'firebase/compat/app';
import 'firebase/compat/auth';
import 'firebase/compat/firestore';

// This file is autogenerated from the user's prompt.
// To use this, you must have a Firebase project with Firestore and Authentication (Email/Password) enabled.

const firebaseConfig = {
  apiKey: "AIzaSyAJtReTcdyhm3knKVtLLEqh8T4ziKDzGQY",
  authDomain: "projek1-12563.firebaseapp.com",
  projectId: "projek1-12563",
  storageBucket: "projek1-12563.firebasestorage.app",
  messagingSenderId: "88628060192",
  appId: "1:88628060192:web:87bd170c01eb9f503bdc45",
  measurementId: "G-K85HBDX41T"
};

// Initialize Firebase
if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
}

const auth = firebase.auth();
const firestore = firebase.firestore();

export { auth, firestore };
