// Fix: Import firebase to resolve 'firebase' not defined errors.
import firebase from 'firebase/compat/app';
import 'firebase/compat/auth';
import 'firebase/compat/firestore';

// This file is autogenerated from the user's prompt.
// To use this, you must have a Firebase project with Firestore and Authentication (Email/Password) enabled.

const firebaseConfig = {
  apiKey: "AIzaSyAOV-ykmgk8kl8QvRLXjvg8k4rRg8efTSE",
  authDomain: "unibrilink-app.firebaseapp.com",
  projectId: "unibrilink-app",
  storageBucket: "unibrilink-app.firebasestorage.app",
  messagingSenderId: "114284669090",
  appId: "1:114284669090:web:b8a871fbf3afd26295cffb",
  measurementId: "G-9NQE0SL234"
};

// Initialize Firebase
if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
}

const auth = firebase.auth();
const firestore = firebase.firestore();

export { auth, firestore };